# This file records information about this repo. Its use is described in OEP-55:
# https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html

apiVersion: backstage.io/v1alpha1
# (Required) Acceptable Values: Component, Resource, System
# A repo will almost certainly be a Component.
kind: Component
metadata:
  name: xblock-image-explorer
  description: This XBlock allows you to use an image with hotspots in a course. When the student clicks a hotspot icon, a tooltip containing custom content is displayed.
  annotations:
    # (Optional) Annotation keys and values can be whatever you want.
    # We use it in Open edX repos to have a comma-separated list of GitHub user
    # names that might be interested in changes to the architecture of this
    # component.
    openedx.org/component-type: XBlock
    openedx.org/arch-interest-groups: ''
spec:

  # (Required) This can be a group (`group:<github_group_name>`) or a user (`user:<github_username>`).
  # Don't forget the "user:" or "group:" prefix. Groups must be GitHub team
  # names in the openedx GitHub organization: https://github.com/orgs/openedx/teams

  owner: user:Agrendalath

  # (Required) Acceptable Type Values: service, website, library
  type: library

  # (Required) Acceptable Lifecycle Values: experimental, production, deprecated
  lifecycle: production
